name: Deploy AppScript

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write CLASPRC to file
        run: |
          echo "$CLASPRC_JSON" > $HOME/.clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC }}

      - name: Install clasp
        run: |
          npm install -g @google/clasp

      - name: Clasp Clone
        run: |
          clasp clone ${{ secrets.SCRIPT_ID }} --auth ~/.clasprc.json
          git checkout -- .

      - name: Deploy AppScript project
        run: |
          clasp push --auth ~/.clasprc.json
