name: Deploy Lambda

on:
  workflow_dispatch:

env:
  REALM_NAME: ${{ secrets.REALM_NAME }}
  BASE_URL: ${{ secrets.BASE_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
  LAMBDA_AUTH_KEY: ${{ secrets.LAMBDA_AUTH_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create environment variable
        run: |
          envsubst < .env.tpl > .env

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: |
            -c "serverless plugin install --name serverless-dotenv-plugin && \
              serverless plugin install --name serverless-python-requirements && \
              serverless deploy"
          entrypoint: /bin/sh
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
