name: Deploy AppScript

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ~/.clasprc.json
        run: |
         echo "${{ secrets.CLASPRC }}" > ~/.clasprc.json

      - name: Install clasp
        run: |
          npm install -g @google/clasp

      - name: Clasp Clone
        run: |
          clasp clone ${{ secrets.SCRIPT_ID }}
          git checkout -- .

      - name: Deploy AppScript project
        run: |
          clasp push
