name: User Creation

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0

      - name: Install Dependencies
        run: pip install -r requirements.txt
