name: User Creation

on:
  push:
  pull_request:

env:
  REALM_NAME: ${{ secrets.REALM_NAME }}
  BASE_URL: ${{ secrets.BASE_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create users from Keycloak API
        run: |
          echo "Creating users"
          python main.py
